name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

env:
    RUSTFLAGS: -Dwarnings

jobs:
    build_and_test:
        name: Build and test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                rust: [nightly, beta, stable]

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Install rust ${{ matrix.rust }}
              uses: actions-rust-lang/setup-rust-toolchain@v2
              with:
                  toolchain: "${{ matrix.rust }}"

            - name: Install Ceph
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y cephadm
                  sudo cephadm add-repo --release tentacle
                  sudo apt-get install -y --no-install-recommends uuid-runtime ceph-mgr ceph-mon ceph-osd ceph-mds librados-dev libradosstriper-dev

            - name: check
              run: cargo clippy --all-targets -- -Dwarnings

            - name: check rados_striper
              run: cargo clippy --features rados_striper --all-targets -- -Dwarnings

            - name: tests
              run: cargo test --all-targets --all-features

    cross:
        name: Cross compile
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - i686-unknown-linux-gnu
                    - armv7-unknown-linux-gnueabihf
                    - aarch64-unknown-linux-gnu

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Install rust
              uses: actions-rust-lang/setup-rust-toolchain@v2
              with:
                  toolchain: stable
                  target: "${{ matrix.target }}"

            - name: Install cross
              run: cargo install cross --git https://github.com/cross-rs/cross

            - name: check
              run: cross clippy --all-targets --target ${{ matrix.target }}

    check_fmt_and_docs:
        name: Checking fmt and docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Install rust
              uses: actions-rust-lang/setup-rust-toolchain@v2
              with:
                  toolchain: stable

            - name: fmt
              run: cargo fmt --all -- --check
